services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8081:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82-service
            - mysql8-service
        networks:
            - nginx-php82-mysql8
    php82-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php82-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - nginx-php82-mysql8
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "3309:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --mysql_native_password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - nginx-php82-mysql8
    varnish-service:
        image: varnish:stable
        volumes:
            - ./varnish/varnish.vcl:/etc/varnish/default.vcl
        container_name: varnish-container
        depends_on:
            - nginx-service
        links:
            - nginx-service
        ports:
            - 8080:80
        networks:
            - nginx-php82-mysql8
    composer:
        image: composer
        volumes:
            - ./app:/app
        command: install
networks:
    nginx-php82-mysql8:
